### PR TITLE
Fix(Invoke-Git.ps1): Add support for network drives

### PR DESCRIPTION
**Pull request by JefeDavis**

### CODE REVIEW

**Comment by virtualguywithabowtie** [comment]
This commit would allow Invoke-Git to be used with PSDrives and network drives

**Comment by RamblingCookieMonster** [comment]
Hiyo!

Makes sense to me.  Leaving this open for another day or two, will merge if there are no objections.

Cheers!

**Comment by DropBearHunta** [comment]
Thanks man! I also added support for modules with powercli dependencies in runspaces, usually it errors out saying the drives are already in use, reimporting does the trick for some reason

**Comment by DropBearHunta** [comment]
Hey there! Wondering if we can get this merged soon

**Comment by RamblingCookieMonster** [comment]
Hiyo!  Sorry, I’m slow!

On a phone, my only concern was how PowerShell handles types in catch statements.  Would that cause any trouble in a system without PowerCLI (or whatever module that comes from), in the odd event that it errored and hit the catch?  Will do a quick test early this week if I find time!

**Comment by DropBearHunta** [comment]
My reasoning was that the catch just retries the import again which if for some reason that didn't work, it would fail to import the module and error out the same way it does now. And the catch itself is tied to the specific exception of drives being already in use, so if another module has that same issue this fix would either work for them or they would be in the same situation as they already are

**Comment by DropBearHunta** [comment]
Hey there! Just wondering if there's any update, waiting on these changes for my build pipeline

**Comment by DropBearHunta** [comment]
Hey @RamblingCookieMonster just wanted to know if this can be merged soon, I'd like to start using it in my pipeline but it's unusable without this fix

**Comment by RamblingCookieMonster** [comment]
Hiyo!  Yeah, figured this would be the case - if a system doesn't have PowerCLI, that code will complain if any error is thrown, given that  `VMware.VimAutomation.ViCore.Cmdlets.Provider.Exceptions.DriveException` doesn't exist.

Feel free to submit the PR without that error handling, or with modified error handling that detects `$_`s type name in the catch block (not with the built in language, just use an if statement or something like that), and runs again if it was `VMware.VimAutomation.ViCore.Cmdlets.Provider.Exceptions.DriveException`.

Cheers!

Warren

**Comment by DropBearHunta** [comment]
Something like that?

**Comment by DropBearHunta** [comment]
looks like AppVeyor is having some issues

**Comment by RamblingCookieMonster** [comment]
Closer!  That still fails - instead of using types, just need to use strings, e.g. something like this might work in the catch block:

`$_.gettype().fullname -eq 'VMware.VimAutomation.ViCore.Cmdlets.Provider.Exceptions.DriveException'`

**Comment by DropBearHunta** [comment]
I think i have it now, what do you think?

**Comment by DropBearHunta** [comment]
Hey there! Any chance we can merge this?

**Comment by DropBearHunta** [comment]
Hey there! Any update on if we can merge this?

**Comment by DropBearHunta** [comment]
Hey @RamblingCookieMonster, Just wondering if we can merge this now?

**Pull request closed without merging**
