### PR TITLE
fix for issue #53

### PR DESCRIPTION
**Pull request by scrthq**
Force path resolution for $Name to prevent relative path errors

### CODE REVIEW

**Comment by RamblingCookieMonster** [comment]
Hmm - just thinking - do you think anyone calls this without specifying an explicit path (i.e. relying on PSModulePath)?  This would break if so.

Personally think using anything but a path would be less than optimal (what if more than one matching module in path, and wrong one is resolved?), but might be worth allowing for it (try resolve path, fall back to name alone?).

If we want to force resolve path everywhere, I'd be okay with it personally, just needs some minor comment-based help updates

Cheers!

**Comment by scrthq** [comment]
I've never run into it personally but I think that's mainly due to following an expected approach and leveraging this with AppVeyor in my build process. I think something like this is good to have in place though as it's non-impacting to have and resolves issues like @gaelcolas 's issue #53

**Comment by scrthq** [comment]
Totally fine with this being kaboshed though if it's not the best idea to solve the issue at hand, corner-case as it may be.

**Comment by RamblingCookieMonster** [comment]
Alrighty, given that this seems to mostly be used with defaults (i.e. path based), and that doing things without a path is more prone to error (i.e. you rely on runtime psmodulepath resolution), I'm happy to flip it to this

Just going to update [the help](https://github.com/scrthq/BuildHelpers/blob/2f11107f03daff7a4c5dc171ffdece3df3997b3d/BuildHelpers/Public/Set-ModuleFunctions.ps1#L13) to mention it, unless you get to it before me

Thanks!

**Comment by RamblingCookieMonster** [comment]
Wheee!  Sorry, I'm slow, merging now, thanks!

**Pull request merged**
