### PR TITLE
Added Set-CodeCoverageBadge function

### PR DESCRIPTION
**Pull request by markwragg**
Per this blog post: 
- http://wragg.io/add-a-code-coverage-badge-to-your-powershell-deployment-pipeline/

This PR is to introduce a `Set-CodeCoverageBadge` function which can be used to update a code coverage badge on your readme.md with the current code coverage percentage result and an associated colour. Example usage in your build pipeline:
```
$CodeFiles = (Get-ChildItem $ENV:BHModulePath -Recurse -Include "*.psm1","*.ps1").FullName
$TestResults = Invoke-Pester -Path $ProjectRoot\Tests -CodeCoverage $CodeFiles -PassThru

$CoveragePercent = [math]::floor(100 - (($TestResults.CodeCoverage.NumberOfCommandsMissed / $TestResults.CodeCoverage.NumberOfCommandsAnalyzed) * 100))

Set-CodeCoverageBadge -CodeCoverage $CoveragePercent  
```

I've also added a basic Pester test for this new function.

### CODE REVIEW

**Comment by RamblingCookieMonster** [comment]
Awesome idea!  Will try to flip through this at lunch today or tomorrow : D

**Comment by lipkau** [comment]
I would suggest using CodeCov.io for the badge.
Mark Kraus and I am working on this: https://github.com/markekraus/CodeCovIo

**Comment by Midacts** [comment]
Line 63, is it possible to not hardcoded the Test Results string?

It might be possible to use this for multiple badges:
- Build
- Code coverage
- Docs
- etc

**Comment by markwragg** [comment]
I did consider that but it might be tricky to incorporate the variables in that string.

**Comment by Midacts** [comment]
Would something like this be acceptable?
https://gist.github.com/Midacts/ef0eb1d30f9234c9dd2433a2129187a1

It makes it so:
- You can name the badge whatever you want
- It checks for the badge name you specify (idk what you would call whats in the image brackets - ![Test Coverage]
- Only adds the percentage for badges with numeric values
- I removed the __type__ [int] on the codecoverage param and renamed it status (to match the name on shield.io) so i could do the `$Status -is [int]` to conditionally add in the Percentage
- Added in "Pass" to the switch case for non numeric values ("pass" == Green and any other words are failures or we can add other cases to the switch)
- Added in the BadgeRegex as a variable that inserts the $BadgeName variable (i created this variable and swapped it for BadgeRegex)

**Comment by markwragg** [comment]
@Midacts great idea. I've done a refactor of the function and have renamed it to Set-ShieldsIoBadge as its now more generic. I've change the parameter names to match how they are referenced on shields.io: subject, status and color (and i've made it so you can manually specify colour). Let me know what you think.

**Comment by RamblingCookieMonster** [comment]
Awesome!  Looks good from here - will try to merge this in tonight

Side note!  there's no real governance model in place, but essentially if someone adds a file here, I sort of assume they have ownership over it and will tag them if folks open related issues/PRs (until they tell me not to : P)

**Comment by markwragg** [comment]
That's fine with me :).

**Comment by Midacts** [comment]
Looks good to me.
The aspercentage makes sense.

Thanks for adding this so I can start adding this to our builds.

**Comment by RamblingCookieMonster** [comment]
Awesome, thanks @markwragg @Midacts : ) merged!

**Pull request merged**
