### PR TITLE
Added function to create persistent variable for VSTS task

### LINKED ISSUE #14: Make build environment variables persistent in VSTS
When using multiple tasks in Visual Studio Team Foundation you need to persist the variables using specific VSTS tasks.

$env:variablename only lives in the current task.
using [VSTS tasks](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md) makes the variable persistent cross tasks.

I propose to add VSTS specific logic to the Set-BuildEnvironment function to make those persistent?
What do you think?

### PR DESCRIPTION
**Pull request by lipkau**
closes #14

### CODE REVIEW

**Comment by RamblingCookieMonster** [comment]
lgtm, thanks!

**Comment by lipkau** [comment]
@vexx32 : I am not convinced it was this PR that broke your pipeline.

I also have no idea which value could not be castable to string.
I created PR #95. This adds `-Verbose` to the command and we can debug this.
sorry for the inconvenience.

**Comment by lipkau** [comment]
problem fixed in #95

**Comment by vexx32** [comment]
Appreciate it very much, thank you!

Not a huge deal for me personally, but I'm sure others could have been affected as well, so thank you! ❤️

**Pull request merged**
