### PR TITLE
add Teamcity as build helper

### PR DESCRIPTION
**Pull request by Plork**
see https://github.com/RamblingCookieMonster/BuildHelpers/issues/6

I do make some assumptions on the build configuration. No solution yet if you bundle commits @ Teamcity

### CODE REVIEW

**Comment by Plork** [comment]
anything wrong with the PR?

**Comment by RamblingCookieMonster** [comment]
Not that I can see!  I'm just slow, will try to merge it in later today - thanks for writing this!

**Comment by Plork** [comment]
no worries,
just wondering since after this I can just pull the latest from the gallery
in my build script ;)

Op ma 1 aug. 2016 om 13:57 schreef Warren F. <notifications@github.com>:

**Comment by RamblingCookieMonster** [comment]
Gotcha! Yeah, have another change staged to deploy as well - the holdup is that I want to write a few quick tests (primarily around Get-BuildVariables at the moment) - code looks good, but would be helpful to have actual tests.

Hopefully lunch today.  Worst case scenario I'll have some time this coming week. Sorry about the delay!

Cheers!

**Comment by Plork** [comment]
I will see if either use a dummy prop file to get some tests going or mock
the result of Get-TeamcityProperties function (or both). (not too much
experience with writing Pester tests.)

Op di 2 aug. 2016 om 14:01 schreef Warren F. <notifications@github.com>:

**Comment by RamblingCookieMonster** [comment]
Going to merge this, wait for build to succeed, maybe tweak a few things, and deploy to the gallery if everything looks good - thanks again!

**Pull request merged**
